neighbors = {
    'alabama': {'florida','georgia','mississippi','tennessee'},
    'alaska': {},
    'arizona': {'california','colorado','nevada','new mexico','utah'},
    'arkansas': {'louisiana','mississippi','missouri','oklahoma','tennessee','texas'},
    'california': {'arizona','nevada','oregon'},
    'colorado': {'arizona','kansas','nebraska','new mexico','oklahoma','utah','wyoming'},
    'connecticut': {'massachusetts','new york','rhode island'},
    'delaware': {'maryland','new jersey','pennsylvania'},
    'florida': {'alabama','georgia'},
    'georgia': {'alabama','florida','north carolina','south carolina','tennessee'},
    'hawaii': {},
    'idaho': {'montana','nevada','oregon','utah','washington','wyoming'},
    'illinois': {'indiana','iowa','kentucky','missouri','wisconsin'},
    'indiana': {'illinois','kentucky','michigan','ohio'},
    'iowa': {'illinois','minnesota','missouri','nebraska','south dakota','wisconsin'},
    'kansas': {'colorado','missouri','nebraska','oklahoma'},
    'kentucky': {'illinois','indiana','missouri','ohio','tennessee','virginia','west virginia'},
    'louisiana': {'arkansas','mississippi','texas'},
    'maine': {'new hampshire'},
    'maryland': {'delaware','pennsylvania','virginia','west virginia'},
    'massachusetts': {'connecticut','new hampshire','new york','rhode island','vermont'},
    'michigan': {'indiana','ohio','wisconsin'},
    'minnesota': {'iowa','north dakota','south dakota','wisconsin'},
    'mississippi': {'alabama','arkansas','louisiana','tennessee'},
    'missouri': {'arkansas','illinois','iowa','kansas','kentucky','nebraska','oklahoma','tennessee'},
    'montana': {'idaho','north dakota','south dakota','wyoming'},
    'nebraska': {'colorado','iowa','kansas','missouri','south dakota','wyoming'},
    'nevada': {'arizona','california','idaho','oregon','utah'},
    'new hampshire': {'maine','massachusetts','vermont'},
    'new jersey': {'delaware','new york','pennsylvania'},
    'new mexico': {'arizona','colorado','oklahoma','texas','utah'},
    'new york': {'connecticut','massachusetts','new jersey','pennsylvania','vermont'},
    'north carolina': {'georgia','south carolina','tennessee','virginia'},
    'north dakota': {'minnesota','montana','south dakota'},
    'ohio': {'indiana','kentucky','michigan','pennsylvania','west virginia'},
    'oklahoma': {'arkansas','colorado','kansas','missouri','new mexico','texas'},
    'oregon': {'california','idaho','nevada','washington'},
    'pennsylvania': {'delaware','maryland','new jersey','new york','ohio','west virginia'},
    'rhode island': {'connecticut','massachusetts'},
    'south carolina': {'georgia','north carolina'},
    'south dakota': {'iowa','minnesota','montana','nebraska','north dakota','wyoming'},
    'tennessee': {'alabama','arkansas','georgia','kentucky','mississippi','missouri','north carolina','virginia'},
    'texas': {'arkansas','louisiana','new mexico','oklahoma'},
    'utah': {'arizona','colorado','idaho','nevada','new mexico','wyoming'},
    'vermont': {'massachusetts','new hampshire','new york'},
    'virginia': {'kentucky','maryland','north carolina','tennessee','west virginia'},
    'washington': {'idaho','oregon'},
    'west virginia': {'kentucky','maryland','ohio','pennsylvania','virginia'},
    'wisconsin': {'illinois','iowa','michigan','minnesota'},
    'wyoming': {'colorado','idaho','montana','nebraska','south dakota','utah'},
}